Repository schmittjoh/JMSSerializerBundle, pull requests merged in 2018-05, with the labels that each got.

#645 Proposal: Add priorities feature to handlers
  DependencyInjection/Compiler/CustomHandlersPass.php
  Tests/DependencyInjection/CustomHandlerPassTest.php
  Tests/DependencyInjection/Fixture/UserDefined/UserDefinedSubscribingHandler.php
  composer.json
Labels: enhancement

#658 Fix serialization handler registration by priority
  DependencyInjection/Compiler/CustomHandlersPass.php
  Tests/DependencyInjection/CustomHandlerPassTest.php
Labels: bug

#652 Compatibility with jms/serializer 2.0
  .travis.yml
  ContextFactory/ConfiguredContextFactory.php
  DependencyInjection/Compiler/CustomHandlersPass.php
  DependencyInjection/Compiler/RegisterEventListenersAndSubscribersPass.php
  DependencyInjection/Compiler/ServiceMapPass.php
  DependencyInjection/Compiler/TwigExtensionPass.php
  DependencyInjection/Configuration.php
  DependencyInjection/JMSSerializerExtension.php
  JMSSerializerBundle.php
  Resources/config/services.xml
  Resources/doc/configuration.rst
  Resources/doc/installation.rst
  Tests/ContextFactory/ConfiguredContextFactoryTest.php
  Tests/DependencyInjection/DoctrinePassTest.php
  Tests/DependencyInjection/EventSubscribersAndListenersPassTest.php
  Tests/DependencyInjection/Fixture/SubscribingHandler.php
  Tests/DependencyInjection/JMSSerializerExtensionTest.php
  Tests/DependencyInjection/NamingStrategyTest.php
  Tests/DependencyInjection/TwigExtensionPassTest.php
  composer.json
  phpunit.xml.dist
Labels: BC Break
